kind: ReplicationController
apiVersion: v1
metadata:
  name: cluster-insight-controller
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cluster-insight
        version: v2
    spec:
      containers:
        - name: cluster-insight
          image: dzozin/cluster-insight:testing
          command:
            - python
          args:
            - ./collector.py
            - --debug
          ports:
            - name: cluster-insight
              containerPort: 5555
